o2online:
  user: <telephone>
  password: <password>


file:
  "SMS-2001.txt":
    :pattern: '^(\"(.*)\" <)?([0-9]+)>?\n(.+)\n(.*)\n\n'
    :mapping:
      sender_name: $1
      sender_nr: $2
      date: $3
      text: $4
